# Generated by Django 4.1.5 on 2023-01-10 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('code', models.CharField(max_length=20, verbose_name='Reservation code')),
                ('checkin_date', models.DateTimeField(null=True, verbose_name='Checkin date')),
                ('checkout_date', models.DateTimeField(null=True, verbose_name='Checkout date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total price')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('number_guests', models.IntegerField(verbose_name='Number of guests')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.advert', verbose_name='Property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
