# Generated by Django 4.1.5 on 2023-01-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_advert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total price'),
        ),
    ]
