# Generated by Django 4.1.5 on 2023-01-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('activated_date', models.DateTimeField(null=True, verbose_name='Activated date')),
                ('cleaning_value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cleaning value')),
                ('accepts_animals', models.BooleanField(default=False, verbose_name='Accept animals?')),
                ('max_number_guests', models.IntegerField(verbose_name='Max. Number of guests')),
                ('bathrooms', models.IntegerField(verbose_name='Bathroomss')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
