# Generated by Django 4.1.5 on 2023-01-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='activated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Activated date'),
        ),
    ]
