# Generated by Django 4.1.5 on 2023-01-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_activated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='cleaning_value',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cleaning value'),
        ),
    ]
