# Generated by Django 4.1.5 on 2023-01-10 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('platform', models.CharField(max_length=100, verbose_name='Platform')),
                ('platform_tax', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='platform tax')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property', verbose_name='Property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
